groups:
- name: application-alerts
  rules:
  - alert: HighResponseTime
    expr: histogram_quantile(0.95, rate(django_http_requests_latency_seconds_bucket[5m])) > 2
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Latence élevée sur {{ $labels.path }} ({{ $value }}s)"

  - alert: LowThroughput
    expr: rate(django_http_requests_total[5m]) < 0.1
    for: 10m
    labels:
      severity: warning
    annotations:
      summary: "Débit de requêtes faible"
      description: "Le débit de requêtes est inférieur à 0.1 req/s depuis 10 minutes"
 
  - alert: HighServerErrorRate
    expr: (sum(rate(django_http_requests_total{status=~"5.."}[5m])) / sum(rate(django_http_requests_total[5m]))) * 100 > 5
    for: 5m
    labels:
      severity: warning
    annotations:
      description: "Taux d'erreur HTTP > 5%"

  - alert: HighClientErrorRate
    expr: rate(django_http_requests_total{status=~"4.."}[5m]) > 5
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Taux élevé d'erreurs client"
      description: "Plus de 5 erreurs client (4xx) par minute détectées"

  - alert: HighCPUUsage
    expr: 100 - (avg by(instance)(rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
    for: 10m
    labels:
      severity: warning
    annotations:
      description: "Utilisation CPU > 80%"

  - alert: HighMemoryUsage
    expr: node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100 < 20
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Mémoire disponible faible"
      description: "Moins de 20% de mémoire disponible sur {{ $labels.instance }}"

  - alert: SlowPageLoad
    expr: rate(page_load_seconds_sum[5m]) / rate(page_load_seconds_count[5m]) > 1
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Temps de chargement des pages élevé"
      description: "Le temps moyen de chargement des pages dépasse 1 seconde"

  - alert: ServiceDown
    expr: up{job="django"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Service Django indisponible"

  - alert: HighFailedLoginRate
    expr: rate(failed_login_attempts_total[5m]) > 5
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Tentatives de connexion échouées"
      description: "Plus de 5 tentatives de connexion échouées par minute détectées"