route:
  group_by: [alertname]
  receiver: 'discord'
  group_wait: 10s
  group_interval: 5m

receivers:
- name: 'discord'
  webhook_configs:
  - url: 'URL_WEBHOOK_DISCORD'
    send_resolved: true