global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['localhost:9093']

rule_files:
  - alerts.yml

scrape_configs:
  - job_name: 'django'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:8000']
    labels:
      app: 'e5-demo'

  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']